######### This is a template sram config file which is used to generate other macros and larger srams composed of multiple macros #########
# synthesis settings
synthesis:
  inputs.input_files: [~/rad_gen/unit_tests/inputs/sram/rtl/sram.sv]
  inputs.top_module: sram_wrapper
  clock_gating_mode: "empty"
# place and route settings
par.innovus.design_flow_effort: "express"

vlsi.inputs:
  # SRAM Settings
  sram_parameters: "~/rad_gen/unit_tests/inputs/sram/configs/mem_params.json"
  sram_parameters_meta: ["transclude", "json2list"]

  power_spec_mode: "auto"
  power_spec_type: "cpf"
  clocks : [
    {
      name: "clk",
      period: "0.0 ns",
    }
  ]
  # Hard Macros require specified placement constraints for top level & instantiated macros 
  placement_constraints:
  - path: "sram_wrapper"
    type: toplevel
    x: 0
    y: 0
    width: 500
    height: 500
    margins:
      left: 0
      right: 0
      top: 0
      bottom: 0
  - path: "sram_wrapper/mem_0_0"
    type: hardmacro
    x: 20
    y: 20
    orientation: "r0"
    top_layer: "M4"
    master: "SRAM1RW1024x16"
  pin_mode: generated
  pin.generate_mode: semi_auto
  pin.assignments: [
    {pins: "*", layers: ["M5", "M7"] ,side: "bottom"}
  ]

